os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-add-repository -y ppa:roblib/ppa
  - sudo apt-get -qq update
  - lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt551
      && sudo apt-get -qq update
      && sudo apt-get -qq install qt55declarative qt55tools qt55svg
      ;

before_script:
   - QTDIR="/opt/qt55" PATH="$QTDIR/bin:$PATH"
      && qt55-env.sh
      && qmake
      ;
script:
  - make -j2 -k
notifications:
  email: false
